<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216162053 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE story_tag (story_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (story_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_A74D17C9AA5D4036 ON story_tag (story_id)');
        $this->addSql('CREATE INDEX IDX_A74D17C9BAD26311 ON story_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B7832B36786B ON tag (title)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B783989D9B62 ON tag (slug)');
        $this->addSql('ALTER TABLE story_tag ADD CONSTRAINT FK_A74D17C9AA5D4036 FOREIGN KEY (story_id) REFERENCES story (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE story_tag ADD CONSTRAINT FK_A74D17C9BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE story_tag DROP CONSTRAINT FK_A74D17C9AA5D4036');
        $this->addSql('ALTER TABLE story_tag DROP CONSTRAINT FK_A74D17C9BAD26311');
        $this->addSql('DROP TABLE story_tag');
        $this->addSql('DROP TABLE tag');
    }
}
